### ISSUE TITLE
FireLooper.java: read from field 'ActivityThread$ActivityClientRecord.activity' on a null object reference

### ISSUE THREAD

**Issue by aemxn** [osama-raddad/FireCrasher#10]
I'm using Crashlytics to capture exception in my app and FireCrasher to catch uncaught exceptions.

Due to a random error from our users, which I'm not sure where it was caused, I'm getting this error in `FireLooper.java:77` from Crashlytics report.

Any idea why?

```
Non-fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.app.Activity android.app.ActivityThread$ActivityClientRecord.activity' on a null object reference
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java)
       at android.app.ActivityThread.access$1100(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at com.osama.firecrasher.FireLooper.run(FireLooper.java:77)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by osama-raddad** [comment]
this is a none issue from google code , doesn't effect the  app on any way

**Comment by osama-raddad** [comment]
This issue is fixed

**Comment by MichaelJokAr** [comment]
@osama-raddad how do you fixed this bug?

**Comment by pikitgb** [comment]
@osama-raddad what was the work around to  fix this ? Thanks a lot
