### ISSUE TITLE
Unfortunately App has stopped

### ISSUE THREAD

**Issue by rubinnellikunnathu** [osama-raddad/FireCrasher#7]
i just created a sample app to check the genuinity of your library.

```
package com.ruben.crashfree;
import android.app.Activity;
import android.app.Application;
import android.widget.Toast;
import com.osama.firecrasher.CrashListener;
        import com.osama.firecrasher.FireCrasher;

public class App extends Application {
    @Override
    public void onCreate() {
        FireCrasher.install(this, new CrashListener() {

            @Override
            public void onCrash(Throwable throwable, final Activity activity) {
                Toast.makeText(activity, throwable.getMessage(), Toast.LENGTH_SHORT).show();

                // start the recovering process
                recover(activity);

                //you need to add your crash reporting tool here
                //Ex: Crashlytics.logException(throwable);
            }
        });
        super.onCreate();
    }
}
```

Then i added a settitle to produce nullpointer exception

```
package com.ruben.crashfree;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

public class MainActivity extends AppCompatActivity{

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getActionBar().setTitle("egergreg");
    }
    public void crash(View view) throws Exception {
        throw new Exception();
    }
}

```

But still my App crashed . and logcat shows.

```
06-02 12:23:22.060 2991-2991/com.ruben.crashfree E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ruben.crashfree, PID: 2991
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ruben.crashfree/com.ruben.crashfree.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2348)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5351)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference
                                                                       at com.ruben.crashfree.MainActivity.onCreate(MainActivity.java:13)
                                                                       at android.app.Activity.performCreate(Activity.java:6012)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5351) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 

```

**Comment by osama-raddad** [comment]
could you send me your build.gradle file ?

**Comment by osama-raddad** [comment]
did you set the name of your application class in the project manifest ?

ex :

```
<application
        android:name=".app"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
```

**Comment by rubinnellikunnathu** [comment]
build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.ruben.crashfree"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.osama.firecrasher:firecrasher:1.0'
}

```

**Comment by rubinnellikunnathu** [comment]
Manifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ruben.crashfree">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by rubinnellikunnathu** [comment]
Yes , I set the name of application class in the project manifest. 
Now my app works perfectly .

But one more doubt, 
on crashing it must show a toast ??

because  

```
@Override
            public void onCrash(Throwable throwable, final Activity activity) {
                Toast.makeText(activity, throwable.getMessage(), Toast.LENGTH_SHORT).show();

                // start the recovering process
                recover(activity);

                //you need to add your crash reporting tool here
                //Ex: Crashlytics.logException(throwable);
            }
```

**But app just restarts with a white screen and doesnt shows any toast message**

**Comment by osama-raddad** [comment]
No you can use your own logic it is just an example

**Comment by osama-raddad** [comment]
The application restart because of the recover method , when the crash happened on the base activity the application will restart but if there is any other activities in the back stack it call the onback method
